quarkus.http.port=8181

quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = ${QUARKUS_DATASOURCE_USERNAME:joao}
quarkus.datasource.password = ${QUARKUS_DATASOURCE_PASSWORD:joao}
quarkus.datasource.reactive.url = postgresql://${QUARKUS_DATASOURCE_HOST:localhost}:${QUARKUS_DATASOURCE_PORT:5432}/agencia
quarkus.devservices.enabled=false

#Rabbit MQ
mp.messaging.outgoing.notificacoes.connector=smallrye-rabbitmq
mp.messaging.outgoing.notificacoes.exchange.type=direct
mp.messaging.outgoing.notificacoes.default-routing-key=agencia.change_status
mp.messaging.outgoing.notificacoes.host=localhost
mp.messaging.outgoing.notificacoes.port=5672

#Kafka
mp.messaging.outgoing.remover-agencia-channel.connector=smallrye-kafka
mp.messaging.outgoing.remover-agencia-channel.topic=remover-agencia-avro
mp.messaging.outgoing.remover-agencia-channel.value.serializer=io.confluent.kafka.serializers.KafkaAvroSerializer
mp.messaging.outgoing.remover-agencia-channel.auto.register.schemas=true
mp.messaging.outgoing.remover-agencia-channel.bootstrap.servers=${QUARKUS_KAFKA_HOST:localhost}:${QUARKUS_KAFKA_PORT:9092}


#Schema Registry
mp.messaging.outgoing.remover-agencia-channel.schema.registry.url=http://localhost:8081
mp.messaging.outgoing.remover-agencia-channel.value.type=br.com.alura.Agencia